title: Informatique en 2ème année de BCPST
author: Quentin Fortier
logo: cobra.webp

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: bcpst2.tex

html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://cpge-itc.github.io/bcpst2
  extra_navbar: ""

repository:
  url: https://github.com/cpge-itc/bcpst2 
  path_to_book: files
  branch: main

launch_buttons:
  basthon_url: "https://notebook.basthon.fr"
  thebe: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
